### ISSUE TITLE
Scrollable areas

### ISSUE THREAD

**Issue by 14rry** [14rry/TopDownRPG#4]
Create levels bigger than single screen in which camera scrolls with the player movement (maybe lerp camera a bit).

**Comment by Citycoder007** [comment]
wtf r u doing coding at 238am
________________________________

**Comment by 14rry** [comment]
working in cd57921f3f8935034b4a4a4883b84af674cb1295

**Comment by 14rry** [comment]
so that's who you are I was wondering who was watching this
